### PR TITLE
fix `unescape_value`

### LINKED ISSUE #6: Escape sequences are not processed correctly when deserializing
I tried this code:
```rust
use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Serialize, Deserialize)]
struct Message {
    msg: String
}

fn main() {
    let source = Message {
        msg: "\\t".into()
    };

    let ini = serini::to_string(&source).unwrap();
    let result: Message = serini::from_str(&ini).unwrap();
    assert_eq!(result, source);
}
```

I expected the last `assert_eq` to succeed, since it's essentially just a roundtrip, with structure being simple enough for the conversion to be lossless. Instead, it fails with this error:
```
assertion `left == right` failed
  left: Message { msg: "\t" }
 right: Message { msg: "\\t" }
```
That is, this file:
```ini
msg = \\t
```
...is deserialized as if it was this:
```ini
msg = \t
```

### PR DESCRIPTION
**Pull request by cafce25**
This fixes #6

### CODE REVIEW

**Comment by peanutbother** [comment]
Thanks for providing a fix, I need to look into the code and check some of the tests before I can merge it.
Other than that looks good!

File: src/lib.rs [hunk 1]
```diff
@@ -634,4 +634,40 @@ mod tests {
...
+        let bs_octo = r#"\#"#;
+
+        let test = RoundtripTest {
+            bs_bs: bs_bs.into(),
+            bs_n: bs_n.into(),
+            bs_r: bs_r.into(),
+            bs_t: bs_t.into(),
+            bs_dquot: bs_dquot.into(),
+            bs_semi: bs_semi.into(),
+            bs_octo: bs_octo.into(),
```
Comment (peanutbother) [inline src/lib.rs]: please replace `.into()` with `.to_string()`

**Review by peanutbother — CHANGES_REQUESTED** [review]
Thanks for your work!
So far I only need to nag about the `.into()` calls but everything else is fine :)
